name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run lint:eslint
        npm run build:pro
        
    - name: ssh-deploy
      uses: easingthemes/ssh-deploy@main
      env:
        # ssh remote host
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        # ssh remote user
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ALI }}
        # source to copy
        SOURCE: dist/
        # destination for copy
        TARGET: /var/www/daoxiangli.com
        SCRIPT_AFTER: |
          echo $PATH > /workspace/temp.txt
        
        
        
